Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: launch-wizard-1
      GroupDescription: launch-wizard-1 created 2025-01-02T17:10:20.280Z
      VpcId: vpc-0c33bfe30ce0c760d
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 103.203.172.27/32

  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-053b12d3152c0cc71
      InstanceType: t2.micro
      KeyName: VijayWebservers
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            Encrypted: false
            DeleteOnTermination: true
            Iops: 3000
            SnapshotId: snap-07423dcbb7214f668
            VolumeSize: 8
            VolumeType: gp3
            Throughput: 125
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref WebServerSecurityGroup
      CreditSpecification:
        CPUCredits: standard
      Tags:
        - Key: Name
          Value: Web server1
      MetadataOptions:
        HttpEndpoint: enabled
        HttpPutResponseHopLimit: 2
        HttpTokens: required
      PrivateDnsNameOptions:
        HostnameType: ip-name
        EnableResourceNameDnsARecord: true
        EnableResourceNameDnsAAAARecord: false
      

1. WebServerSecurityGroup: This resource creates the security group with the specified name, description, and VPC ID. It also configures the ingress rule to allow TCP traffic on port 22 from the specified IP address.

2. WebServerInstance: This resource creates the EC2 instance with the specified configurations, including the AMI ID, instance type, key pair name, block device mapping, network interface (associated with the security group), CPU credit specification, tags, metadata options, and private DNS name options.

